apiVersion: v1
kind: Secret
metadata:
  name: pulsewatch-secrets
  namespace: pulsewatch
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgrespassword@postgres-service:5432/pulsewatch?sslmode=disable"
  REDIS_URL: "redis://redis-service:6379/0"
  JWT_SECRET: "k8s-prod-super-secret-jwt-key-pulsewatch-2026"
