# Build Stage
FROM golang:1.26.5-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/api ./cmd/api

# Final Stage
FROM alpine:3.19
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/api /app/api
COPY --from=builder /app/docs /app/docs
COPY --from=builder /app/web /app/web

EXPOSE 8080
ENTRYPOINT ["/app/api"]
